# Generated by Django 4.0.1 on 2022-04-24 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('warehouseid', models.IntegerField(default=0, null=True)),
                ('userx', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('usery', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('finish', models.IntegerField(default=0, null=True)),
                ('change', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truckid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('truckx', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('trucky', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userx', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('usery', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='truckid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ups.truck'),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
